version: 2
updates:
  #  Main branch
  - package-ecosystem: maven
    directory: "/hero-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/villain-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/fight-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/fight-ui"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/fight-ui/src/main/webapp"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"