@startsalt
{
{
T
super-heroes
+  rest-hero
++  src
+++  main
++++  docker
+++++  Dockerfile.jvm
+++++  Dockerfile.native
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  hero
++++++++++  HeroResource.java
++++  resources
+++++  META-INF
++++++  resources
+++++++  index.html
+++++  application.properties
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  hero
++++++++++  HeroResourceTest.java
++++++++++  NativeHeroResourceIT.java
++  mvnw
++  mvnw.cmd
++  pom.xml
}
}
@endsalt