@startsalt
{
{
T
hero-service
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  hero
+++++++++  HeroResource.java
+++++++++  Hero.java
++++  resources
+++++  application.properties
+++++  import.sql
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  hero
+++++++++  HeroResourceIT.java
+++++++++  HeroResourceTest.java
++ Dockerfile
++ README.md
++ catalog-info.yaml
++ mvnw
++ mvnw.cmd
++ openapi.yaml
++ pom.xml
}
}
@endsalt