@startsalt
{
{
T
hero
++  src
+++  main
++++  docker
+++++  Dockerfile.jvm
+++++  Dockerfile.legacy-jar
+++++  Dockerfile.native
+++++  Dockerfile.native-micro
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  hero
+++++++++  HeroResource.java
++++  resources
+++++  application.properties
+++++  import.sql
+++  test
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  hero
+++++++++  HeroResourceIT.java
+++++++++  HeroResourceTest.java
++ Dockerfile
++ README.md
++ catalog-info.yaml
++ mvnw
++ mvnw.cmd
++ openapi.yaml
++ pom.xml
}
}
@endsalt