apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fight-ui

spec:
  to:
    kind: Service
    name: fight-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None