@startsalt
{
{
T
super-heroes
+  rest-hero
++  src
+++  main
++++  java
+++++  io
++++++  quarkus
+++++++  workshop
++++++++  superheroes
+++++++++  hero
++++++++++  Hero.java
++++++++++  HeroResource.java
++  pom.xml
}
}
@endsalt