name: Build

env:
  JVM_VERSION: '21'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/**'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - hero-service
          - villain-service
          - fight-service

    name: "Build ${{ matrix.app }}"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin
          cache: maven

      - name: Maven Build for ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -DskipITs=false
